sudo: required

env:
  global:
  - REPO=nominatim-docker
  - TAG=v2.0.$TRAVIS_BUILD_NUMBER

script:
- cd 3.3/
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker --version  
- pip install --user awscli
- export PATH=$PATH:/$HOME/.local/bin
- eval $(aws ecr get-login --registry-ids $AWS_ACCOUNT_NUMBER --region eu-west-2 --no-include-email)
- docker tag $REPO:$TAG $AWS_ACCOUNT_NUMBER.dkr.ecr.eu-west-2.amazonaws.com/$REPO:$TAG
- docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.eu-west-2.amazonaws.com/$REPO:$TAG
